name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - release
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.1
        with:
          version: latest
